<div class="o-search__inner">
	<form role="search" method="get" class="o-search__form js-search-form" action="<?php echo esc_url(home_url('/')); ?>">
		<label for="search" class="o-search__label h-vh"><? _e('Search', 'nxtheme'); ?></label>
		<input id="search" type="search" class="o-search__input js-search-input"
		       placeholder="Suchbegriff"
		       value="<?php echo esc_attr(get_search_query()); ?>" name="s">
	</form>
	<button class="o-search__button__close js-search" role="button" aria-label="<?= esc_attr_x('Search', 'placeholder', 'nxtheme'); ?>"></button>
</div>
