<?php

	if (is_single()) {
		global $post; ?>

		<meta property="og:site_name" content="<?php wp_title('|', true, 'right'); ?>" />
		<meta property="og:description" content="<?php
			$content_post = get_post($post->ID);
			$content = strip_tags(apply_filters('the_content', $content_post->post_content));
			echo substr($content, 0, 80).'...';
			?>"/>

		<?php
		$facebook_thumbnail = '';
		if (function_exists('wp_get_attachment_image_src')) {
			$image_attributes = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'facebook_thumbnail' );
			if ($image_attributes) {
				$facebook_thumbnail = $image_attributes[0];
			}
		}
		?>

		<meta property="og:image" content="<?php echo $facebook_thumbnail ?>" />
<?php } else { ?>
		<meta property="og:site_name" content="<?php wp_title('|', true, 'right'); ?>" />
		<meta property="og:description" content="<?php bloginfo('description'); ?>" />
<?php } ?>